spring.application.name=nubank

spring.datasource.url=jdbc:postgresql://localhost:5432/nubank?currentSchema=financeiro
spring.datasource.username=nubank
spring.datasource.password=nubank
spring.datasource.driver-class-name=org.postgresql.Driver

